---
# Installation tasks for Ubuntu
# https://www.percona.com/doc/percona-server/5.7/installation/apt_repo.html
# https://www.percona.com/doc/percona-server/8.0/installation/apt_repo.html

- name: "Install gnupg"
  apt:
    name: gnupg2
    update_cache: yes

- name: "Install percona-release package"
  apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Configure Percona repo for PXC"
  ansible.builtin.shell: percona-release enable-only pxc-80 release

- name: "Configure Percona repo for tools"
  ansible.builtin.shell: percona-release enable tools release

- name: "Update apt cache"
  apt:
    update_cache: yes

# https://www.percona.com/doc/percona-server/LATEST/installation/apt_repo.html
#- name: "Enable Percona repository (Percona version >= 8)"
#  command: "percona-release setup ps{{ mysql_version_major }}{{ mysql_version_minor }}"
#  when: mysql_version_major|int >= 8
#  changed_when: False     # TODO: check for task idempotency

- name: "Install python-is-python3 (Ubuntu >= Focal/20.04)"
  apt:
    name: "python-is-python3"
  when:
    - ansible_distribution_version is version_compare('20.04', '>=')

- debug:
    msg: "ansible_python_interpreter major version: {{ ansible_python.version.major }}"

- name: "Install package dependencies for ansible MySQL modules (python 2)"
  apt:
    name: "python-mysqldb"
  when:
    - ansible_python.version.major == 2     # version is a number, do not quote

- name: "Install package dependencies for ansible MySQL modules (python 3)"
  apt:
    name: 
      - "python3-pymysql"
      - "python3-mysqldb"
  when:
    - ansible_python.version.major == 3     # version is a number, do not quote

- name: "Install percona cluster packages, ProxySQL and dependencies on Ubuntu"
  apt:
    name:
      - "percona-xtradb-cluster"
      - "percona-xtradb-cluster-client"
      - "proxysql2"
    state: "present"
  when: mysql_version_major|int >= 8

- name: "Install mc, percona-toolkit and Percona Xtrabackup"
  apt:
    name:
      - percona-xtrabackup-80
      - mc
      - percona-toolkit
      - zstd
      - lz4
    update_cache: yes

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0700
    state: "directory"