---
- include_tasks: check-settings.yml
  tags: check
  when: ansible_os_family not in ['RedHat', 'Rocky']

- include_tasks: check-settings-centos.yml
  tags: check
  when: ansible_os_family in ['RedHat', 'Rocky']

- include_tasks: install.yml
  tags: install
  when: ansible_os_family not in ['RedHat', 'Rocky']

- include_tasks: install-centos.yml
  tags: install
  when: ansible_os_family in ['RedHat', 'Rocky']

- include_tasks: configure.yml
  tags: configure
  when: ansible_os_family not in ['RedHat', 'Rocky']

- include_tasks: configure-centos.yml
  tags: configure
  when: ansible_os_family in ['RedHat', 'Rocky']

- include_tasks: secure.yml
  tags: secure

- include_tasks: databases.yml
  tags: databases

- include_tasks: users.yml
  tags: users